# Generated by Django 3.1.4 on 2020-12-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Phone',
            field=models.CharField(default='DEFAULT VALUE', max_length=12),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.CharField(max_length=72),
        ),
    ]
