# Generated by Django 3.1.4 on 2020-12-31 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20201231_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
    ]
